### ISSUE TITLE
This cycle is not required. You could only change length

### ISSUE THREAD

**Issue by AlexYalovoy** [RuQuentin/tests_MyArray#19]
https://github.com/RuQuentin/tests_MyArray/blob/e778c8e98d9cfcc250247b7cc68938ee8902f603/src/index.js#L6

**Comment by RuQuentin** [comment]
It was just my attempt to make empty values, because you know, an Array shows you that it has a number of empty values.
I still am not sure if we need such thing or not. For example, if I create an Array(8) - it has 8 empty members.
Then if I apply FIND to this array - I'll still get 8 iterations during looking a target value. But if I don't add these empty (undefined) values in MyArray - I won't have these iterations. The same is for other methods, I think.
http://joxi.ru/vAWbEpLC1P8Ej2
Well, I'm not really sure that it's useful, but this is just the reason why I've done it )))
