### ISSUE TITLE
Too many if constructions. Try to optimize code length.

### ISSUE THREAD

**Issue by AlexYalovoy** [RuQuentin/tests_MyArray#26]
https://github.com/RuQuentin/tests_MyArray/blob/e778c8e98d9cfcc250247b7cc68938ee8902f603/src/index.js#L237

**Comment by RuQuentin** [comment]
I'll think about it again, but I'm not sure that it is possible here. I've noticed, that people, whose code I reviewed, haven't taken into account these checks:
  if (begin < 0 && Math.abs(begin) < this.length) {
    from = this.length + begin;
}

and 

  if (end >= 0 && end <= this.length) {
    to = end;
}

And if you put too big positive or negative number, you'll get empty (undefined) members in your new array. So, this checks limit these cases so that you won't get this empty (undefined) members like in real array.

**Comment by AlexYalovoy** [comment]
Actually, i agree with you.
You need these two checks to avoid unwanted consequences
